package main

import "fmt"

func main() {
	fmt.Println("Starting exercise01...")
	exercise01()
	fmt.Println("Done exercise01!")
	fmt.Println("\n----------------------")
	fmt.Println("Starting exercise02...")
	exercise02()
	fmt.Println("Done exercise02!")
	fmt.Println("\n----------------------")
	fmt.Println("Starting exercise03...")
	exercise03()
	fmt.Println("Done exercise03!")
	fmt.Println("\n----------------------")
	fmt.Println("Starting exercise04...")
	exercise04()
	fmt.Println("Done exercise04!")
	fmt.Println("\n----------------------")
	fmt.Println("Starting exercise05...")
	exercise05()
	fmt.Println("Done exercise05!")
	fmt.Println("\n----------------------")
	fmt.Println("Starting exercise06...")
	exercise06()
	fmt.Println("Done exercise06!")
	fmt.Println("\n----------------------")
	fmt.Println("Starting exercise07...")
	exercise07()
	fmt.Println("Done exercise07!")
	fmt.Println("\n----------------------")
	fmt.Println("Starting exercise08...")
	exercise08()
	fmt.Println("Done exercise08!")
	fmt.Println("\n----------------------")
	fmt.Println("Starting exercise09...")
	exercise09()
	fmt.Println("Done exercise09!")
	fmt.Println("\n----------------------")
	fmt.Println("Starting exercise10...")
	exercise10()
	fmt.Println("Done exercise10!")
	fmt.Println("\n----------------------")
	fmt.Println("Starting exercise11...")
	exercise11()
	fmt.Println("Done exercise11!")
	fmt.Println("\n----------------------")
}
